openapi: 3.0.3
info:
  title: Report Service API
  description: API for financial reports and aggregated queries
  version: 1.0.0
servers:
  - url: http://localhost:8085
    description: Local server
paths:
  /api/reports/balances/customer/{customerId}:
    get:
      summary: Get customer's financial product balances
      description: Retrieves balances for accounts, credit cards and loans associated with a customer
      operationId: getCustomerBalances
      parameters:
        - name: customerId
          in: path
          required: true
          description: Customer ID
          schema:
            type: string
      responses:
        '200':
          description: Balances retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseCustomerBalances'
        '404':
          description: No balances found for customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseCustomerBalances'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseCustomerBalances'
  /api/reports/movements/customer/{customerId}/product/{productId}:
    get:
      summary: Get movements for a financial product
      description: Retrieves movements associated with a customer's account, credit card or loan
      operationId: getProductMovements
      parameters:
        - name: customerId
          in: path
          required: true
          description: Customer ID
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: Financial product ID
          schema:
            type: string
      responses:
        '200':
          description: Movements retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseProductMovements'
        '404':
          description: No movements found for product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseProductMovements'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseProductMovements'
  /api/reports/{customerId}/summary:
    get:
      summary: Get monthly balance summary
      description: Retrieves monthly balance summary for a customer
      operationId: getMonthlyBalanceSummary
      parameters:
        - name: customerId
          in: path
          required: true
          description: Customer ID
          schema:
            type: string
      responses:
        '200':
          description: Summary retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DailyBalanceSummary'
        '404':
          description: No summary found
          content:
            application/json:
              schema:
                type: string
  /api/reports/transactions/summary:
    get:
      summary: Get transaction summary by date range
      description: Retrieves transaction summary for a specific date range
      operationId: getTransactionSummary
      parameters:
        - name: startDate
          in: query
          required: true
          description: Start date (ISO format)
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          description: End date (ISO format)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Transaction summary retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseCategorySummary'
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        data:
          type: object
    BaseResponseCustomerBalances:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/CustomerBalances'
    BaseResponseProductMovements:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/ProductMovement'
    BaseResponseCategorySummary:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/CategorySummary'
    CustomerBalances:
      type: object
      properties:
        customerId:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductBalance'
    ProductBalance:
      type: object
      properties:
        productId:
          type: string
        type:
          type: string
          enum: [ACCOUNT, CREDIT, CREDIT_CARD]
        subType:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM, PERSONAL_CREDIT, BUSINESS_CREDIT, PERSONAL_CREDIT_CARD, BUSINESS_CREDIT_CARD]
        availableBalance:
          type: number
          format: decimal
    ProductMovement:
      type: object
      properties:
        transactionId:
          type: string
        date:
          type: string
          format: date-time
        amount:
          type: number
          format: decimal
        productCategory:
          type: string
          enum: [ACCOUNT, CREDIT, CREDIT_CARD]
        productSubType:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM, PERSONAL_CREDIT, BUSINESS_CREDIT, PERSONAL_CREDIT_CARD, BUSINESS_CREDIT_CARD]
        type:
          type: string
          enum: [DEPOSIT, WITHDRAWAL, CREDIT_PAYMENT, CREDIT_CARD_PURCHASE, TRANSFER]
    CategorySummary:
      type: object
      properties:
        category:
          type: string
        quantity:
          type: integer
        commissions:
          type: number
          format: double
    DailyBalanceSummary:
      type: object
      properties:
        productId:
          type: string
        productType:
          type: string
        subType:
          type: string
        averageBalance:
          type: number
          format: decimal